name: "Rust CI"

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    name: "Rust CI"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Set up Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy

      - name: Check license headers
        run: ./scripts/check-license.sh

      - name: Check code formatting
        run: cargo fmt --check

      - name: Run clippy linter
        run: cargo clippy --all-targets -- -D warnings

      - name: Run test suite
        run: cargo test

